'use strict';

/**
 * AI Service Layer - NeuroAdapt Backend
 * 
 * Single source of truth for all AI text simplification interactions.
 * Integrates with Groq API.
 * Implements strict input validation, response cleaning, 10s timeouts, 
 * and automatic API key rotation for failover and rate limits.
 */

const prompts = {
  basic: `Rewrite for a 10-year-old.
Max 12 words per sentence.
Replace all jargon.
Use active voice only.
Return ONLY the rewritten text.`,

  standard: `Rewrite in plain English for a general reader.
Keep technical terms only if unavoidable.
Briefly explain difficult terms.
Maximum 18 words per sentence.
Return ONLY the rewritten text.`,

  academic: `Lightly simplify this text.
Preserve terminology.
Improve clarity and sentence structure.
Return ONLY the rewritten text.`
};

/**
 * Retrieves valid Groq API keys from environment variables.
 * @returns {string[]} Array of API keys
 */
function getAvailableGroqKeys() {
  const keys = [];
  for (const [key, value] of Object.entries(process.env)) {
    if (key.startsWith('GROQ_API_KEY_') && value && value.trim() !== '') {
      keys.push(value.trim());
    }
  }
  return keys;
}

/**
 * Cleans the response generated by the LLM, removing common preambles and trims whitespace.
 * @param {string} text - Raw text from the LLM.
 * @returns {string} Cleaned text.
 */
function cleanResponse(text) {
  if (typeof text !== 'string') return '';
  let cleaned = text.trim();

  // Common preambles to strip case-insensitively from the beginning
  // and handle potential surrounding markdown or punctuation.
  const preambles = [
    /^(?:here\s+is\s+the\s+simplified\s+version:?)/i,
    /^(?:here's\s+the\s+simplified\s+version:?)/i,
    /^(?:simplified\s+text:?)/i,
    /^(?:rewritten\s+text:?)/i,
    /^(?:output:?)/i,
    /^(?:result:?)/i
  ];

  let changed = true;
  while (changed) {
    changed = false;
    const current = cleaned;
    for (const regex of preambles) {
      cleaned = cleaned.replace(regex, '').trim();
    }
    if (cleaned !== current) {
      changed = true;
    }
  }

  // Remove quotes wrapping the entire response if the LLM added them
  if (
    (cleaned.startsWith('"') && cleaned.endsWith('"')) ||
    (cleaned.startsWith("'") && cleaned.endsWith("'"))
  ) {
    cleaned = cleaned.slice(1, -1).trim();
  }

  // Remove markdown code blocks if the LLM returned it wrapped (e.g. ```text ... ``` or ``` ...)
  const codeBlockRegex = /^```(?:\w+)?\n([\s\S]*?)\n```$/;
  const match = cleaned.match(codeBlockRegex);
  if (match) {
    cleaned = match[1].trim();
  }

  return cleaned;
}

/**
 * Interacts with the Groq API to simplify text.
 * @param {string} text - Input text.
 * @param {string} level - Simplification level.
 * @param {string} language - Target language.
 * @returns {Promise<string>} Simplified and cleaned text.
 */
async function callGroqWithRotation(text, level, language) {
  const keys = getAvailableGroqKeys();
  if (keys.length === 0) {
    console.error('[Groq] No API keys configured');
    throw new Error('AI_SERVICE_UNAVAILABLE');
  }

  const url = 'https://api.groq.com/openai/v1/chat/completions';
  const levelPrompt = prompts[level] || prompts.standard;
  const systemInstruction = `Respond only in ${language}.
Do NOT add any introduction.
Do NOT add any preamble.
Do NOT say:
* Here is the simplified version
* Simplified text:
* Rewritten text:
Return ONLY the rewritten content.`;

  const promptText = `${levelPrompt}\n\nText to rewrite:\n${text}`;

  const body = {
    model: process.env.GROQ_MODEL || 'llama-3.3-70b-versatile',
    messages: [
      {
        role: 'system',
        content: systemInstruction
      },
      {
        role: 'user',
        content: promptText
      }
    ],
    temperature: 0.3,
    max_tokens: 500
  };

  // Iterate over keys for automatic failover
  for (let i = 0; i < keys.length; i++) {
    const apiKey = keys[i];
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000);

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify(body),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      // Handle successful response
      if (response.ok) {
        const data = await response.json();
        const generatedText = data.choices?.[0]?.message?.content;

        if (!generatedText || typeof generatedText !== 'string' || generatedText.trim() === '') {
          throw new Error('GROQ_EMPTY_RESPONSE');
        }

        return cleanResponse(generatedText);
      }

      // Handle retryable errors
      const status = response.status;
      if (status === 401 || status === 429) {
        console.warn(`[Groq] Key ${i + 1} failed with status ${status}. Rotating to next key...`);
        continue;
      }
      
      const errorText = await response.text().catch(() => '');
      // Some quota/rate limit errors might return 400 or 403 depending on the exact proxy,
      // so explicitly check error text as a safety net.
      const lowerError = errorText.toLowerCase();
      if (lowerError.includes('quota') || lowerError.includes('rate limit')) {
        console.warn(`[Groq] Key ${i + 1} hit quota/rate limit. Rotating to next key...`);
        continue;
      }

      // Unretryable error (e.g. bad request)
      throw new Error(`Groq API returned unrecoverable status ${status}: ${errorText}`);
      
    } catch (error) {
      clearTimeout(timeoutId);
      
      // If AbortError (Timeout) or Network Error (fetch failed), rotate to next key
      if (error.name === 'AbortError' || error.message.includes('fetch')) {
        console.warn(`[Groq] Key ${i + 1} experienced network/timeout error. Rotating...`);
        continue;
      }

      // If it's a specific empty response, maybe the model just hallucinated, skip to next key
      if (error.message === 'GROQ_EMPTY_RESPONSE') {
        console.warn(`[Groq] Key ${i + 1} returned empty response. Rotating...`);
        continue;
      }
      
      // Throw unexpected errors to the outer scope (but we don't expose them to clients)
      console.error(`[Groq] Unexpected error on Key ${i + 1}:`, error.message);
      continue;
    }
  }

  // All keys exhausted
  console.error('[Groq] All available API keys have been exhausted or failed.');
  throw new Error('AI_SERVICE_UNAVAILABLE');
}

/**
 * Simplifies input text using LLMs, handling validation, latency tracking, 
 * and automatic API key rotation.
 * 
 * @param {string} text - Text to simplify.
 * @param {string} [level='standard'] - Simplification level ('basic', 'standard', 'academic').
 * @param {string} [language='English'] - Target language.
 * @returns {Promise<{success: boolean, simplifiedText: string, provider: string, latencyMs: number}>}
 */
async function simplifyText(text, level = 'standard', language = 'English') {
  // Input Validation
  if (text === null || text === undefined || typeof text !== 'string' || text.trim() === '') {
    throw new Error('INVALID_TEXT_INPUT');
  }

  // Ensure chosen level is supported (fall back to standard if invalid)
  const chosenLevel = prompts[level] ? level : 'standard';

  const startTime = Date.now();

  try {
    const simplified = await callGroqWithRotation(text, chosenLevel, language);
    const latencyMs = Date.now() - startTime;
    return {
      success: true,
      simplifiedText: simplified,
      provider: 'groq',
      latencyMs
    };
  } catch (error) {
    if (error.message === 'INVALID_TEXT_INPUT') throw error;
    throw new Error('AI_SERVICE_UNAVAILABLE');
  }
}

module.exports = {
  simplifyText
};
